# Generated by Django 2.2.2 on 2019-06-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedrooms',
            new_name='bought_price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='city',
            new_name='env',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='address',
            new_name='hostname',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='made_year',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
        migrations.AddField(
            model_name='listing',
            name='file_1',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='file_2',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='file_main',
            field=models.FileField(default=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='position',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
